import shutil
import sqlite3

from unittest import TestCase

import sqlsn3k.table


class TestTable(TestCase):
    def setUp(self):
        """
        Sets up two tables using well-known queries from a test database
        """
        con = sqlite3.connect('test.db')
        con.row_factory = sqlite3.Row
        self.dims = shutil.get_terminal_size()
        # (Query, Cols, Rows)
        self.cases = [("SELECT * FROM info ORDER BY lap_time ASC", 26, 623),
                      ("SELECT * FROM info WHERE class='Military'", 26, 15)]
        self.tables = list()
        for case in self.cases:
            self.tables.append(sqlsn3k.table.Table(con.execute(case[0])))


class TestInit(TestTable):
    def test_scalars(self):
        """
        Tests that all scalar values generated by the Table constructor are
        correct.
        """
        for i in range(0, len(self.tables)):
            self.assertEqual(self.tables[i].width, self.dims.columns)
            self.assertEqual(self.tables[i].height, self.dims.lines)
            self.assertEqual(self.tables[i].nrows, self.cases[i][2])
            self.assertEqual(self.tables[i].ncols, self.cases[i][1])

    def test_printing(self):
        """
        Prints tables to stdout for manual visual confirmation
        """
        for table in self.tables:
            print('-' * 20)
            for line in table.printable():
                print(line)
